a=prompt("Nhập mã sinh viên");
b=prompt("Nhập tên sinh viên");
c=prompt("Nhập lớp sinh viên");
var td1 = document.getElementById("td1") ;
var td2 = document.getElementById("td2") ;
var td3 =document.getElementById("td3");
td1.innerHTML=a;
td2.innerHTML=b;
td3.innerHTML=c;